language: objective-c
xcode_sdk: iphonesimulator10.1
branches:
  only:
  - master
notifications:
  email: false
before_install:
- SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 7 (10.0) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
- echo "Prelaunching iOS simulator with UDID $SIMULATOR_ID"
- open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID
- gem update bundler
install:
- bundle install
script:
- xcodebuild clean build test -project SymondsStudentApp.xcodeproj -scheme SymondsStudentApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty && exit ${PIPESTATUS[0]}
env:
  global:
    secure: nrYpfd0M41DjkAtMI4q3a62M6cpxL8lHe7WH/BE9/kRHrGJ6lfZURH3/+L0q4IZSic8EJS2/nUL+l/528nVAg9ZxTgWpr0Q8CPbrR5ulfvZLeLBwU2InlzZOr2sURyn9j4aEWdScH3y8Z7BZ62zb0H3Jr13OTh7jN3hy2HsHkOcMzXcrUZk60QcwhJ7J86gczPJIAvF5tNfiYGYbOQ/r1GwiLg2guwEPUPC1vyv/FwH8I8e1EOKLEKC6Y9AzwBtlxiQZskaQdDE1lCmQ37tUE4FDcXdTMTlyP7+dIk63PcaiG3HwSYkWsqlEVZ71UsCDU2sE1LdazH5FP8SO7MmeURuiz0I58MvYay72JwpSIAMO+gLYKUxJ4Y61ku2o8ORKt0QnZWmSn0J1AqMIhfgD+MPmnIUe1T+yvAiv+YD80ya9m7VZmOnUZ/ufOlyNWPKrmrmI1/10BKaJQcxDrSdoLKmamK3v/9Rb8t1Zz9xQCBolDrU9c5YkEG+i4r7ahlcjo5T+tAGZCFZJnOYKyG6tJagVtbFkieoQKfbBO2/0+WU9ijSYhxZBrdHCIIc+syWqOwqymTBfPf/MW/HQGRNaYH1q+hM0dbL0BlWYyGxROE6RD4/92MnQ7IHiMwJ7DOB3faBfwmJga9rM88fqKGwbFUqIWZ07timplrZ8xm/4Ml8=
