language: objective-c
osx_image: xcode9.2
xcode_project: SymondsStudentApp.xcodeproj
xcode_scheme: SymondsStudentApp
branches:
  only:
  - master
  - "/^develop-.*$/"
  - travis
notifications:
  email: false
  slack:
    secure: N6WWUa0xzvNTUNJy/yoybAfy8tTo7wFshwrMt5z0/Uj0fWFvN4C+8SGMBOawLcv2v6j++koZLrrxKSovm79P+y4Ngkkfjm8ACtYlxqGwgQC35tc75WXwo1Y6v+eGw8Sn/UZ3ZSf1Bfzd2aOSF2bw7PVCKEJnLoK7+z9+YYRglEuyx0griQhb2j+rXZWz19BH4fBjHWcWmQITnlFUCEX3hOflmrOYWd4uMDOY+5fg805E8vti/kGWOKKo2iTR+KB6xDKKhuSppqlG2nDPrSo/TnhkVIV6Hu7ycaZRg3IuxLit44i0W5STiaUNSemwZ0xTwTrkFUzYuC0O6zONLD+aLsE8eyDACzRlQkMnW0SX/JAwLch3CNNHgu6KS39dLgbk25KGZ8oTsNW96wQOVx7qugwObNceJNi1WMTFFBA2vpGEHfJKFFfHhe3Kx5yipIRj5ukuznId7LkGsKqdha9KOz+W1tr0l2Sa26vUnIIqjY1w2SxHh3VMe1qA5Ae4ZlB1WZcsWBfF9tNCSr/XgqalmUuYOMsfP5ftto9KvY/+uGDhe2wsPIofUoHJ0gfR0Z4K8P+7tvzqKObVGswBzJhxHRKHv5cpJmbT8SjFiUs89rsVOFOukDs2mygFYqiT5aKYbdKYSgQxKo2NxbN1q0XEg5f3cW1z5iUDGHPbd9/P1V4=
env:
  global:
    secure: QSS8zftQQ9Gdla3EtEroD9gNnsFNQ3a/jAxd2ZtnuSpSaG9sD2qdwAReEVxGCd5FhYkEt+ZN/YNrOscewGKDGu1lPuWMGOvS74dOGJVslHZnSi7SYxZQmeWGsWuGqVq9l6RGm1LMIunMeIQdF1utRBfdEb2qPgIhDimAl9/j0gEnWDMK3Y9I4iqXlT59i1aMSb65Sc01FOyC44Mg58hpYcRAVmxFo/L95UXawUFlGw188Y4gMBJ+KpwLnnseqWV+jFBXqlMWfWxUL97ENxLPP/RotCmL5dpv4ePQjnGK+pvmtS4PTg0oF4SUz/CbYvXh26fOz9GmwR+LwQBSmk1Q2foRkWaSNMQt/aD7PnrlqFt0LQYzsLqcwRnFGI2saWR8gBKIdpJUv2IIb2sERMelprHPlVrx8LHvi8us9N6vrqZ1HagVXZELDn100eC0Gx/BDyOifuYN0zZ9bz6Yg+jPHflC2thgba0Spdrq+R7pANRSeFiiksp/rrziBiS2FjrABdXZWJqtc863laEOdyv1MnQBGTMXk0m0LJwvHAyf83UX+1/GeCO/91Sfq11vnpwvDh0XObK4BRcozR5zaZ9yGQRlMUArFimykiPZWuNEg5JZk22PVf546MWMX7k8qDDRdRx5KX9E8aoItl10tp4tv+jKjsPqCHtfYaEi4Q/dbY8=
