language: objective-c
branches:
  only:
  - master
notifications:
  email: false
before_install:
- SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 7 (10.0) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
- echo "Prelaunching iOS simulator with UDID $SIMULATOR_ID"
- open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID
- gem update bundler
install:
- bundle install
script:
- xcodebuild clean build test -project SymondsStudentApp.xcodeproj -scheme SymondsStudentApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty && exit ${PIPESTATUS[0]}
env:
  global:
    secure: fkwxZBfsTmcEn/gcKhgpr4BLNt1SDdX9wVrYVu55J0FoaE8dFO3hjnxEwdxEXOr5R0n5tkKrelsZWoRL7TgEgj2W1ZrgU68GhA0MoaIUjAyeVhOxrz5rZnVvDZu8hnqC8bLajqmP8KXil2TUDeDiob1lJsC8A+ukLOThtR0QOxMpfaKN5M87VP5fkfWoRg11C3edtptA8ZAgw7FGoLpxSHSJTqO+19unpOHU6vTtdciVM6BGMQnQqhLfy5tfdhrpbNsGBtvwJLnOe/9gcAKw5+khZcVAS/GOEyu9UoUGWoVz+tRSjIsrsQ2Ii0m+yvNx44qYVZbEzsdKRovMcyARxAqRrP1z6TH0L1xpO9SXssU6VrrZK7noaDQRiAR/MwoxXikrIafO8/qBWyCBePhYRDYmon0pLYEK1edmXuwHBlRH1hdybZRgqel6SF54zxi7OLzRB7yg+HOozG7Y0N/DkMtd6IVtEHk/RW/W69Nnf6Lf07SJQU+TIaM+E3DCzWaXla714TR87IR2XDU7+DwM47BoOWubMVzvplx0jAvnFy6LrL73rgcniJdbzbjBDaYtSdymi+JQdgsulcGSqf2qCg8IW3TcId0YK5s2FlAuvVDjFUJE9wCAI1wRyhCLVLq7gpBpYIRNmS18ICavOa2AhU1dC6tkBOIYkvf/oCv8tUg=