os: osx
language: objective-c
osx_image: xcode9.2
branches:
  only:
  - master
  - "/^develop-v.+/"
  - travis
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- gem install bundler
install:
- make get-deps
script:
- bundle exec fastlane ios travis
notifications:
  email: false