os: osx
language: objective-c
osx_image: xcode9.2
branches:
  only:
  - master
  - "/^develop-v.+/"
  - travis
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- gem install bundler
install:
- make get-deps
script:
- bundle exec fastlane ios travis
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: N6WWUa0xzvNTUNJy/yoybAfy8tTo7wFshwrMt5z0/Uj0fWFvN4C+8SGMBOawLcv2v6j++koZLrrxKSovm79P+y4Ngkkfjm8ACtYlxqGwgQC35tc75WXwo1Y6v+eGw8Sn/UZ3ZSf1Bfzd2aOSF2bw7PVCKEJnLoK7+z9+YYRglEuyx0griQhb2j+rXZWz19BH4fBjHWcWmQITnlFUCEX3hOflmrOYWd4uMDOY+5fg805E8vti/kGWOKKo2iTR+KB6xDKKhuSppqlG2nDPrSo/TnhkVIV6Hu7ycaZRg3IuxLit44i0W5STiaUNSemwZ0xTwTrkFUzYuC0O6zONLD+aLsE8eyDACzRlQkMnW0SX/JAwLch3CNNHgu6KS39dLgbk25KGZ8oTsNW96wQOVx7qugwObNceJNi1WMTFFBA2vpGEHfJKFFfHhe3Kx5yipIRj5ukuznId7LkGsKqdha9KOz+W1tr0l2Sa26vUnIIqjY1w2SxHh3VMe1qA5Ae4ZlB1WZcsWBfF9tNCSr/XgqalmUuYOMsfP5ftto9KvY/+uGDhe2wsPIofUoHJ0gfR0Z4K8P+7tvzqKObVGswBzJhxHRKHv5cpJmbT8SjFiUs89rsVOFOukDs2mygFYqiT5aKYbdKYSgQxKo2NxbN1q0XEg5f3cW1z5iUDGHPbd9/P1V4=
env:
  global:
    secure: g9/ANUnsq0nTwkldGoY2rMFpFNgUsnudxdpPLf98ZYcFlZtiWvkEJd5ufANj0JDKIdEUhJwgmR95DfF7v9GYMeTxa+HmVFx264+KdQrM85fcqWieHk4rxDwC437bFuqOuzrONqLYLcURQJWXp+o1uFl7Uao9bgifo/RYdgDCMHL1cb3ki5M5bt4ROAQt34HCxAZ9KPFDBkvPkEXAyEGSLNgS/LefkiWwSXfh+MSomm4iQAdYy2cnxIwAZwtwdiY3GDyAyJHWkhf3GWs8m8hSef0TC2iCPewPEqjWxRPobEjknFn72f90gp6qX4J+T1C5DQ19mlr/dGG7F8My0AVSb8ZX0BAwAx6MmVUhu9nLVTFYygtR//rfnII2vRoSLqi5C3ljojPhJW1W+DK99YN3cNked3pKm9uRtj+DO4PgHlE6dCMEJ3zp5h6gfEL/M3/eB3TOj7Y2dItQT8cbaPkZyrVZFbp96N8OS3iSABFxJEctBbGUhikPthc1FPntEhxUhkvziqpO87iLbr40K8qBPYz9lx9RiUhp1E1VQCEUIMldOJhApQJ7Oba8+gSTmon7PmBV/+kDjva2gv998kKIET1+j12/EvaaNG5pKj3gzl6joDxTkRQ52n6thOlpaKptJx9aWY3zF3bI0mkJgsgXzrC3Ew3ZinAxKSZAgnCV76U=
