//
//  TimetableItemTests.swift
//  SymondsStudentAppTests
//
//  Created by Søren Mortensen on 27/11/2017.
//  Copyright © 2017 Søren Mortensen, George Taylor. All rights reserved.
//

import XCTest
import SymondsStudentApp

class TimetableItemTests: XCTestCase {
    
    func testDecodingNotNil() {
        let decoder = JSONDecoder()
        let decoded = try? decoder.decode([TimetableItem].self, from: allTestItems)
        
        XCTAssertNotNil(decoded)
    }
    
    private var sampleTestItems: Data = """
    [
        {
          "Type": "break",
          "Id": "",
          "Title": "Break",
          "Subtitle": "",
          "Start": 1511778000,
          "End": 1511779200,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562022242",
          "Title": "AS Communication & Culture",
          "Subtitle": "",
          "Start": 1511779200,
          "End": 1511782500,
          "Room": "FR105",
          "Staff": "Mrs Welsh",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511785800,
          "End": 1511787600,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
    ]
    """.data(using: .utf8)!
    
    private var sampleItemsExpected: [TimetableItem] = [
        
    ]
    
    private var allTestItems: Data = """
    [
        {
          "Type": "lesson",
          "Id": "48000561998026",
          "Title": "A Level History (Early)",
          "Subtitle": "",
          "Start": 1511771400,
          "End": 1511774700,
          "Room": "FR103",
          "Staff": "Miss Taylor",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562011006",
          "Title": "AS Law",
          "Subtitle": "",
          "Start": 1511774700,
          "End": 1511778000,
          "Room": "FR104",
          "Staff": "Mr James",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "break",
          "Id": "",
          "Title": "Break",
          "Subtitle": "",
          "Start": 1511778000,
          "End": 1511779200,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562022242",
          "Title": "AS Communication & Culture",
          "Subtitle": "",
          "Start": 1511779200,
          "End": 1511782500,
          "Room": "FR105",
          "Staff": "Mrs Welsh",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562011170",
          "Title": "A Level Psychology",
          "Subtitle": "",
          "Start": 1511782500,
          "End": 1511785800,
          "Room": "FR101",
          "Staff": "Mr Jones",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511785800,
          "End": 1511787600,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511787600,
          "End": 1511790600,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000563998448",
          "Title": "Symonds Lecture Programme (Lower Sixth)",
          "Subtitle": "",
          "Start": 1511790600,
          "End": 1511793900,
          "Room": "FR106",
          "Staff": "",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511793900,
          "End": 1511797200,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511797200,
          "End": 1511800500,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562022242",
          "Title": "AS Communication & Culture",
          "Subtitle": "",
          "Start": 1511857800,
          "End": 1511861100,
          "Room": "FR105",
          "Staff": "Mrs Welsh",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511861100,
          "End": 1511864400,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "break",
          "Id": "",
          "Title": "Break",
          "Subtitle": "",
          "Start": 1511864400,
          "End": 1511865600,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000561998026",
          "Title": "A Level History (Early)",
          "Subtitle": "",
          "Start": 1511865600,
          "End": 1511868900,
          "Room": "FR103",
          "Staff": "Miss Taylor",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562011006",
          "Title": "AS Law",
          "Subtitle": "",
          "Start": 1511868900,
          "End": 1511872200,
          "Room": "FR104",
          "Staff": "Miss French",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "tutorgroup",
          "Id": "48000562087379",
          "Title": "Tutor Group",
          "Subtitle": "",
          "Start": 1511872200,
          "End": 1511874000,
          "Room": "FR107",
          "Staff": "Mr Long",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562135505",
          "Title": "Workshop: A2 Communication & Culture",
          "Subtitle": "",
          "Start": 1511874000,
          "End": 1511877000,
          "Room": "FR105",
          "Staff": "Mrs Welsh",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511877000,
          "End": 1511880300,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511880300,
          "End": 1511883600,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511883600,
          "End": 1511886900,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511944200,
          "End": 1511947500,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511947500,
          "End": 1511950800,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "break",
          "Id": "",
          "Title": "Break",
          "Subtitle": "",
          "Start": 1511950800,
          "End": 1511952000,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562011006",
          "Title": "AS Law",
          "Subtitle": "",
          "Start": 1511952000,
          "End": 1511955300,
          "Room": "FR104",
          "Staff": "Mr James",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000561998026",
          "Title": "A Level History (Early)",
          "Subtitle": "",
          "Start": 1511955300,
          "End": 1511958600,
          "Room": "FR103",
          "Staff": "Miss Taylor",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511958600,
          "End": 1511960400,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511960400,
          "End": 1511963400,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511963400,
          "End": 1511966700,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511966700,
          "End": 1511970000,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1511970000,
          "End": 1511973300,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562011006",
          "Title": "AS Law",
          "Subtitle": "",
          "Start": 1512030600,
          "End": 1512033900,
          "Room": "FR104",
          "Staff": "Miss French",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562011006",
          "Title": "AS Law",
          "Subtitle": "",
          "Start": 1512033900,
          "End": 1512037200,
          "Room": "FR104",
          "Staff": "Mr James",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "break",
          "Id": "",
          "Title": "Break",
          "Subtitle": "",
          "Start": 1512037200,
          "End": 1512038400,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1512038400,
          "End": 1512041700,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562022242",
          "Title": "AS Communication & Culture",
          "Subtitle": "",
          "Start": 1512041700,
          "End": 1512045000,
          "Room": "FR105",
          "Staff": "Mrs Round",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1512045000,
          "End": 1512046800,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562135517",
          "Title": "Workshop: A2 Communication & Culture",
          "Subtitle": "",
          "Start": 1512046800,
          "End": 1512049800,
          "Room": "FR105",
          "Staff": "Mr Thompson",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562011170",
          "Title": "A Level Psychology",
          "Subtitle": "",
          "Start": 1512049800,
          "End": 1512053100,
          "Room": "FR101",
          "Staff": "Mr Hart",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000561998026",
          "Title": "A Level History (Early)",
          "Subtitle": "",
          "Start": 1512053100,
          "End": 1512059700,
          "Room": "FR103",
          "Staff": "Miss Taylor",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562011170",
          "Title": "A Level Psychology",
          "Subtitle": "",
          "Start": 1512117000,
          "End": 1512120300,
          "Room": "FR101",
          "Staff": "Mr Hart",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562011170",
          "Title": "A Level Psychology",
          "Subtitle": "",
          "Start": 1512120300,
          "End": 1512123600,
          "Room": "FR101",
          "Staff": "Mr Jones, Mr Hart",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "break",
          "Id": "",
          "Title": "Break",
          "Subtitle": "",
          "Start": 1512123600,
          "End": 1512124800,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1512124800,
          "End": 1512128100,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1512128100,
          "End": 1512131400,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "tutorgroup",
          "Id": "48000562087379",
          "Title": "Tutor Group",
          "Subtitle": "",
          "Start": 1512131400,
          "End": 1512133200,
          "Room": "FR107",
          "Staff": "Mr Long",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1512133200,
          "End": 1512136200,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "studyperiod",
          "Id": "",
          "Title": "Study Period",
          "Subtitle": "",
          "Start": 1512136200,
          "End": 1512139500,
          "Room": "",
          "Staff": "",
          "IsBlank": true,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
        {
          "Type": "lesson",
          "Id": "48000562022242",
          "Title": "AS Communication & Culture",
          "Subtitle": "",
          "Start": 1512139500,
          "End": 1512146100,
          "Room": "FR105",
          "Staff": "Mrs Round",
          "IsBlank": false,
          "IsCancelled": false,
          "IsRoomChange": false,
        },
    ]
    """.data(using: .utf8)!
    
}
